apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ph9f84gbr-nodejs
  janus-idp.io/tekton: ph9f84gbr-nodejs
  backstage.io/kubernetes-id: ph9f84gbr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ph9f84gbr-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
